name: fast_news_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  html: ^0.15.5
  http: ^1.2.2
  json_annotation: ^4.9.0
  lottie: ^3.2.0
  provider: ^6.1.2
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/svg_icon/
    - assets/lattie/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-Light.ttf
        - asset: fonts/Roboto-Medium.ttf
        - asset: fonts/Roboto-Regular.ttf